# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: nextsimupdate.io
description: >- # this means to ignore newlines until "baseurl:"
  Want to know when the next sim update is? 
  All product and company names are trademarks™ or registered® trademarks of their respective holders. 
  Use of them does not imply any affiliation with or endorsement by them. Microsoft Flight Simulator registered trademarks of Microsoft Corporation 
  in the United States and/or other countries. The site complies with Microsofts Game Content Usage Rules

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  release_dates:
      sort_by: to_date asc
      output: true
      permalink: :name
      order:
        - WorldUpdateVI.md
        - SimUpdateVI.md
        - Patch 1.18.14.0.md
        - SimUpdateV.md
        - WorldUpdateV.md
        - Patch 1.15.8.0.md
        - WorldUpdateIV.md
        - Patch 1.14.6.0.md

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
